### ISSUE TITLE
No servers are responding in any region, always under maintenance 

### ISSUE THREAD

**Issue by kd4pba** [rishabh3354/4KTUBE#1]
Is this application even real? It seems after paying it stops working.  It has been this way for 24 hours

**Comment by rishabh3354** [comment]
Could you please tell me little more about the issue. What exactly issue you are facing in the app?

**Comment by kd4pba** [comment]
It has major issues saying either the servers are under maintenance or the downloads fail and I have to restart them. I don't see any logs I can provide from the application itself. 

OS: Ubuntu Cinnamon 23.10 x86_64 
Kernel: 6.5.0-17-generic 
Uptime: 2 days, 30 mins 
Packages: 4963 (dpkg), 55 (flatpak), 58 (snap) 
Shell: bash 5.2.15 
Resolution: 3440x1440 
DE: Cinnamon 5.8.4 
WM: Mutter (Muffin) 
WM Theme: Cinnazor (Cinnamox-Kashmir-Blue) 
Theme: Adapta-Nokto [GTK2/3] 
Icons: Avalon-Icons [GTK2/3] 
Terminal: tilix 
CPU: AMD Ryzen 5 3600 (12) @ 3.600GHz 
GPU: NVIDIA GeForce RTX 2060 Rev. A 
Memory: 5805MiB / 32011MiB

**Comment by kd4pba** [comment]
You can mark this as resolved This was a DNS issue.
