### ISSUE TITLE
OOPS ! COULD NOT CONNECT TO THE SERVER

### ISSUE THREAD

**Issue by reyou82** [rishabh3354/4KTUBE#3]
voila le message d'erreur qui s'affiche a la connection ,? alors que internet fonctionne parfaitement sur l'ordinateur. impossible de se connecter sur votre serveur ? mise  a jour a effectuer ? comment?

**Comment by reyou82** [comment]
Bonjour,
   juste pour vous remercier de votres réponse, je vous souhaite une tres
bonne journée et pleins pleins de succès pour cette année et .....les année
a venir,

   Cordialement Alain REY

Le mer. 4 janv. 2023 à 16:40, Rishabh Bhardwaj ***@***.***> a
écrit :

**Comment by rishabh3354** [comment]
Thanks @reyou82 . Updates has been pushed. Issue is resolved now, please update your app to see the changes. Thanks for reporting

**Comment by reyou82** [comment]
Bonjour,
désolé de vous importuner mais, je ne voie pas comment mettre à jour ?

 Cordialement

Le jeu. 5 janv. 2023 à 09:03, Rishabh Bhardwaj ***@***.***> a
écrit :

**Comment by rishabh3354** [comment]
It will auto update automatically. 
If you wamt to update manually, Run this cmd in your terminal

sudo snap refresh 4ktube
