### ISSUE TITLE
Question: Difference between 4KTUBE, TUBE2GO & YOUTUBE-DL-PRO

### ISSUE THREAD

**Issue by boustanihani** [rishabh3354/4KTUBE#5]
Question: Difference between 4KTUBE, TUBE2GO & YOUTUBE-DL-PRO

@rishabh3354 I like your work, just one Question, could you please explain the difference between the three apps (other than different downloading engines), **like when to use which one**. The descriptions of all three seem very similar and this is a bit confusing:

https://github.com/rishabh3354/YOUTUBE-DL-PRO
https://github.com/rishabh3354/TUBE2GO
https://github.com/rishabh3354/4KTUBE

**Comment by rishabh3354** [comment]
Go with 4ktube, its the best and all rounder and better download engine

**Comment by boustanihani** [comment]
Thanks a lot
