### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by collaone** [rishabh3354/4KTUBE#6]
Italian correct translation for "CLOSE" is "CHIUDI" not "VICINO".
![image](https://github.com/user-attachments/assets/3ad54205-5d3c-4a8a-ba04-4fd44f8656d7)

**Comment by rishabh3354** [comment]
Thanks for information, it will be updated in the next update

**Comment by collaone** [comment]
I take this opportunity to compliment you, the app is magnificent!

**Comment by rishabh3354** [comment]
You are welcome

**Comment by rishabh3354** [comment]
Thanks for reporting. it is now fixed in new version of the app. i am closing this issue for now.
